"""initial: 创建用例、计划、关联表

Revision ID: 9dd4cf49589d
Revises: 
Create Date: 2026-07-04 17:05:31.575447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd4cf49589d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='用例标题'),
    sa.Column('module', sa.String(length=128), nullable=False, comment='所属模块'),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='priorityenum'), nullable=False, comment='优先级'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', name='casestatusenum'), nullable=False, comment='状态'),
    sa.Column('precondition', sa.Text(), nullable=True, comment='前置条件'),
    sa.Column('steps', sa.JSON(), nullable=False, comment='测试步骤'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_module'), 'test_cases', ['module'], unique=False)
    op.create_table('test_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='计划名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='planstatusenum'), nullable=False, comment='状态'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_plan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_plan_id', sa.Integer(), nullable=False, comment='测试计划ID'),
    sa.Column('test_case_id', sa.Integer(), nullable=False, comment='测试用例ID'),
    sa.Column('execution_status', sa.Enum('PASSED', 'FAILED', 'BLOCKED', 'SKIPPED', name='executionstatusenum'), nullable=True, comment='执行状态'),
    sa.Column('executed_by', sa.String(length=64), nullable=True, comment='执行人'),
    sa.Column('actual_result', sa.Text(), nullable=True, comment='实际结果'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('executed_at', sa.DateTime(), nullable=True, comment='执行时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_plan_id', 'test_case_id', name='uq_plan_case')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_plan_items')
    op.drop_table('test_plans')
    op.drop_index(op.f('ix_test_cases_module'), table_name='test_cases')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
